-- Geoscience 001 - Create demo foundation objects

declare
  procedure exec_if_missing (
    p_object_name in varchar2,
    p_object_type in varchar2,
    p_sql         in clob
  ) is
    l_count number;
  begin
    select count(*)
      into l_count
      from user_objects
     where object_name = upper(p_object_name)
       and object_type = upper(p_object_type);

    if l_count = 0 then
      execute immediate p_sql;
    end if;
  end exec_if_missing;
begin
  exec_if_missing('GS_ENVIRONMENTS', 'TABLE', q'~
    create table gs_environments (
      environment_id       number generated by default on null as identity primary key,
      environment_code     varchar2(20 char) not null,
      environment_name     varchar2(120 char) not null,
      environment_tier     varchar2(30 char) not null,
      status_code          varchar2(30 char) default 'ACTIVE' not null,
      created_at           timestamp with local time zone default systimestamp not null,
      updated_at           timestamp with local time zone default systimestamp not null,
      constraint gs_env_uk_code unique (environment_code),
      constraint gs_env_ck_status check (status_code in ('ACTIVE','PAUSED','RETIRED'))
    )
  ~');

  exec_if_missing('GS_PEOPLE', 'TABLE', q'~
    create table gs_people (
      person_id            number generated by default on null as identity primary key,
      display_name         varchar2(200 char) not null,
      email_address        varchar2(255 char) not null,
      team_name            varchar2(160 char),
      role_name            varchar2(160 char),
      manager_name         varchar2(200 char),
      active_yn            varchar2(1 char) default 'Y' not null,
      created_at           timestamp with local time zone default systimestamp not null,
      updated_at           timestamp with local time zone default systimestamp not null,
      constraint gs_people_uk_email unique (email_address),
      constraint gs_people_ck_active check (active_yn in ('Y','N'))
    )
  ~');

  exec_if_missing('GS_ACCOUNT_REQUESTS', 'TABLE', q'~
    create table gs_account_requests (
      request_id           number generated by default on null as identity primary key,
      request_number       varchar2(40 char) not null,
      person_id            number not null references gs_people(person_id),
      request_type_code    varchar2(30 char) not null,
      requested_by         varchar2(255 char) not null,
      requested_at         timestamp with local time zone default systimestamp not null,
      status_code          varchar2(30 char) default 'DRAFT' not null,
      business_reason      varchar2(2000 char),
      ai_summary           varchar2(2000 char),
      target_due_date      date,
      completed_at         timestamp with local time zone,
      created_at           timestamp with local time zone default systimestamp not null,
      updated_at           timestamp with local time zone default systimestamp not null,
      constraint gs_acct_req_uk_num unique (request_number),
      constraint gs_acct_req_ck_type check (request_type_code in ('ONBOARD','CHANGE','OFFBOARD')),
      constraint gs_acct_req_ck_status check (status_code in ('DRAFT','SUBMITTED','IN_REVIEW','APPROVED','IN_PROGRESS','COMPLETE','BLOCKED','CANCELLED'))
    )
  ~');

  exec_if_missing('GS_ENV_ACCOUNTS', 'TABLE', q'~
    create table gs_env_accounts (
      account_id           number generated by default on null as identity primary key,
      person_id            number not null references gs_people(person_id),
      environment_id       number not null references gs_environments(environment_id),
      username             varchar2(128 char) not null,
      account_status       varchar2(30 char) default 'REQUESTED' not null,
      last_login_at        timestamp with local time zone,
      provisioned_at       timestamp with local time zone,
      deactivated_at       timestamp with local time zone,
      notes                varchar2(2000 char),
      created_at           timestamp with local time zone default systimestamp not null,
      updated_at           timestamp with local time zone default systimestamp not null,
      constraint gs_env_accts_uk unique (person_id, environment_id),
      constraint gs_env_accts_ck_status check (account_status in ('REQUESTED','READY','ACTIVE','LOCKED','DEACTIVATED','ERROR'))
    )
  ~');

  exec_if_missing('GS_APEX_APPLICATIONS', 'TABLE', q'~
    create table gs_apex_applications (
      app_registry_id      number generated by default on null as identity primary key,
      application_id       number,
      application_name     varchar2(200 char) not null,
      application_alias    varchar2(128 char),
      workspace_name       varchar2(128 char) default 'GEOSCIENCE' not null,
      schema_name          varchar2(128 char) default 'GEOSCIENCE' not null,
      app_status           varchar2(30 char) default 'PLANNED' not null,
      active_users_count   number default 0 not null,
      monthly_sessions     number default 0 not null,
      last_health_check_at timestamp with local time zone,
      health_status        varchar2(30 char) default 'UNKNOWN' not null,
      troubleshooting_note varchar2(2000 char),
      created_at           timestamp with local time zone default systimestamp not null,
      updated_at           timestamp with local time zone default systimestamp not null,
      constraint gs_apex_apps_ck_status check (app_status in ('PLANNED','BUILD','ACTIVE','PAUSED','RETIRED')),
      constraint gs_apex_apps_ck_health check (health_status in ('UNKNOWN','PASS','WARN','FAIL'))
    )
  ~');

  exec_if_missing('GS_HEALTH_CHECKS', 'TABLE', q'~
    create table gs_health_checks (
      health_check_id      number generated by default on null as identity primary key,
      app_registry_id      number not null references gs_apex_applications(app_registry_id),
      check_name           varchar2(160 char) not null,
      status_code          varchar2(30 char) not null,
      check_message        varchar2(2000 char),
      checked_at           timestamp with local time zone default systimestamp not null,
      created_by           varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
      constraint gs_health_ck_status check (status_code in ('PASS','WARN','FAIL'))
    )
  ~');

  exec_if_missing('GS_FEEDBACK_ITEMS', 'TABLE', q'~
    create table gs_feedback_items (
      feedback_id          number generated by default on null as identity primary key,
      source_task_key      varchar2(40 char) not null,
      source_application   varchar2(200 char) not null,
      source_page          varchar2(200 char),
      feedback_type        varchar2(40 char) default 'FEEDBACK' not null,
      feedback_title       varchar2(300 char) not null,
      feedback_text        varchar2(4000 char) not null,
      submitted_by         varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
      submitted_at         timestamp with local time zone default systimestamp not null,
      forward_status       varchar2(30 char) default 'CAPTURED' not null,
      idempotency_key      varchar2(255 char),
      ai_hub_task_key      varchar2(40 char),
      public_response      varchar2(4000 char),
      forward_error        varchar2(2000 char),
      constraint gs_feedback_ck_status check (forward_status in ('CAPTURED','QUEUED','FORWARDED','RESPONDED','ERROR'))
    )
  ~');

  exec_if_missing('GS_BOREHOLE_SOURCES', 'TABLE', q'~
    create table gs_borehole_sources (
      source_id            number generated by default on null as identity primary key,
      source_name          varchar2(200 char) not null,
      source_url           varchar2(1000 char),
      source_status        varchar2(30 char) default 'PLANNED' not null,
      last_refresh_at      timestamp with local time zone,
      notes                varchar2(2000 char),
      created_at           timestamp with local time zone default systimestamp not null,
      updated_at           timestamp with local time zone default systimestamp not null,
      constraint gs_bore_src_ck_status check (source_status in ('PLANNED','ACTIVE','PAUSED','ERROR'))
    )
  ~');

  exec_if_missing('GS_BOREHOLES', 'TABLE', q'~
    create table gs_boreholes (
      borehole_id          number generated by default on null as identity primary key,
      source_id            number references gs_borehole_sources(source_id),
      borehole_ref         varchar2(100 char) not null,
      borehole_name        varchar2(240 char),
      state_code           varchar2(20 char),
      region_name          varchar2(160 char),
      latitude             number,
      longitude            number,
      depth_metres         number,
      drilled_year         number,
      commodity_group      varchar2(160 char),
      status_code          varchar2(40 char) default 'KNOWN' not null,
      source_updated_at    timestamp with local time zone,
      created_at           timestamp with local time zone default systimestamp not null,
      updated_at           timestamp with local time zone default systimestamp not null,
      constraint gs_boreholes_uk_ref unique (borehole_ref),
      constraint gs_boreholes_ck_status check (status_code in ('KNOWN','ACTIVE','HISTORIC','REVIEW','ERROR'))
    )
  ~');

  exec_if_missing('GS_DATA_REFRESH_RUNS', 'TABLE', q'~
    create table gs_data_refresh_runs (
      refresh_run_id       number generated by default on null as identity primary key,
      source_id            number references gs_borehole_sources(source_id),
      refresh_type         varchar2(40 char) not null,
      status_code          varchar2(30 char) default 'STARTED' not null,
      requested_by         varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
      started_at           timestamp with local time zone default systimestamp not null,
      finished_at          timestamp with local time zone,
      rows_loaded          number default 0 not null,
      rows_rejected        number default 0 not null,
      message              varchar2(2000 char),
      constraint gs_refresh_ck_type check (refresh_type in ('MANUAL_UPLOAD','REMOTE_REFRESH','SEED_DATA')),
      constraint gs_refresh_ck_status check (status_code in ('STARTED','SUCCESS','WARN','FAILED'))
    )
  ~');

  execute immediate q'~
    create or replace view gs_account_dashboard_v as
    select r.status_code,
           r.request_type_code,
           count(*) request_count,
           min(r.requested_at) oldest_request_at,
           max(r.requested_at) latest_request_at
      from gs_account_requests r
     group by r.status_code, r.request_type_code
  ~';

  execute immediate q'~
    create or replace view gs_environment_account_v as
    select p.display_name,
           p.email_address,
           e.environment_code,
           e.environment_name,
           a.username,
           a.account_status,
           a.last_login_at,
           a.provisioned_at
      from gs_env_accounts a
      join gs_people p on p.person_id = a.person_id
      join gs_environments e on e.environment_id = a.environment_id
  ~';

  execute immediate q'~
    create or replace view gs_borehole_summary_v as
    select state_code,
           region_name,
           commodity_group,
           count(*) borehole_count,
           round(avg(depth_metres), 1) avg_depth_metres,
           min(drilled_year) first_drilled_year,
           max(drilled_year) latest_drilled_year
      from gs_boreholes
     group by state_code, region_name, commodity_group
  ~';

  execute immediate q'~
    create or replace view gs_feedback_queue_v as
    select feedback_id,
           source_task_key,
           source_application,
           source_page,
           feedback_type,
           feedback_title,
           submitted_by,
           submitted_at,
           forward_status,
           ai_hub_task_key,
           public_response
      from gs_feedback_items
  ~';
end;
